### ISSUE TITLE
Discord Webhook

### ISSUE THREAD

**Issue by Bims-sh** [CGB-CoolGamerBoy/CGB-Hub-Whitelist#1]
Hey there, I found your discord webhook url in the [Register.lua](https://github.com/CGB-CoolGamerBoy/CGB-Hub-Whitelist/blob/main/Register.lua) in plain text, consider disabling the webhook and generating a new url which isn't publicly available on GitHub.

Best regards.

**Comment by CGB-CoolGamerBoy** [comment]
I believe the webhook is disabled

**Comment by CGB-CoolGamerBoy** [comment]
Yea it's disabled. This repository is just for open source whitelist now. I don't use it anymore

**Comment by Bims-sh** [comment]
Ah, I checked and it was apparently active.
Well anyways, have a good one 👍
